# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Compile all java files with junit
      - name: Compile and Build Project
        run: |
          cd Projects 
          cd P3
          javac -d ./out -cp "src/" src/*.java

  run_tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Compile all java files with junit
      - name: Compile and Build Project
        run: |
          cd Projects 
          cd P3
          mv tests/* .
          mv src/*.java .
          echo "compiling java src files"
          javac -cp "junit-4.10.jar:." *.java
